### ISSUE TITLE
Buffers not displayed

### ISSUE THREAD

**Issue by bartbutenaers** [rikukissa/node-red-contrib-image-output#3]
Hi Riku,

Sorry to disturb you again.

Will first start with good news.  When I use my [node-red-contrib-multipart-stream-decoder](https://github.com/bartbutenaers/node-red-contrib-multipart-stream-decoder/) node to get an MJPEG stream from my camera, your node still works ***great*** at **10** images per second:

![image](https://user-images.githubusercontent.com/14224149/36105622-5ae94940-1015-11e8-969b-017b4621af03.png)

But when I add your node directly behind my decoder node (which sends images as buffers) and before the base64 encoder, no image is displayed:

![image](https://user-images.githubusercontent.com/14224149/36105238-65bfb49a-1014-11e8-9c49-f1c4df91aa28.png)
Some thoughts about this:
+ Are you sure that the node's input can be both a (not base64 encoded) Buffer or a base64 encoded string?
+ If the input is not correct, perhaps you can log an error or display a (red) node status.  Because now you cannot see immediately if there is no input, or whether the input is incorrect...
+ Perhaps you could also display something like this to make it very user friendly (but only a nice to have):

    ![image](https://user-images.githubusercontent.com/14224149/36105592-434be9a0-1015-11e8-97f9-70742038491f.png)

Now I will stop posting issues for today ;-)

Kind regards,
Bart

**Comment by bartbutenaers** [comment]
Hi @rikukissa,

The first of my 3 above questions is not valid.  Did the test again and now it seems to be working fine:

![image](https://user-images.githubusercontent.com/14224149/36356174-2f8cea9e-14ee-11e8-956f-c60ceb1ec5d1.png)

Don't know what I did wrong in my previous test.  So it works fine both with Buffers and base64 encoded strings!

Kind regards,
Bart

**Comment by rikukissa** [comment]
Oh, good to hear it works! I was just about to start debugging this, but maybe I'll focus on the other issues you've created :) 100% appreciate your input. Keep it coming!

**Comment by rikukissa** [comment]
> If the input is not correct, perhaps you can log an error or display a (red) node status. Because now you cannot see immediately if there is no input, or whether the input is incorrect...

Yup, you're absolutely right. It should be useful to get some feedback of why the node isn't working as expected. I'd imagine this would've also helped you when you came across your issue.

> Perhaps you could also display something like this to make it very user friendly (but only a nice to have)

Totally! I actually found myself needing to fill in empty inputs with a transparent image Buffer while I was using this, which definitely isn't ideal.

Would you have time to drop me a PR addressing these things? Otherwise I can also fix these, but it might take me a while :)

**Comment by bartbutenaers** [comment]
Deal ;-)
I will create a pull request for both items, but need some extra input:
+ I will display an error in the node status if the input is not correct.  So the input needs to be a Buffer or a base64 encoded string ??  But when I look at your code the _payload is **always** encoded to a base64 encoded string_:
    `data: msg.payload.toString("base64")`

   However in my flow screenshot above, I have used a base64 encoder node.  So the payload is base64 encoded twice: one time by the base64 encoder node, and once by your node.  And it seems to work fine.  Don't understand it at the moment ;-(   

    Need that information, to know what the input needs to be:
    ```
    if ( !Buffer.isBuffer(msg.payload) &&  ?????????) {
          node.error("Input should be a Buffer or a ??????????", msg);
          node.status({fill:"red",shape:"ring", "Invalid input"});
    }
    ```
+ About the 'no preview available' image.  Would you add such an image to the Github repository and push it (at the start of the flow) to the editor.  Or would you prefer to draw it using SVG in the browser, as soon as the editor is started?

Bart

**Comment by rikukissa** [comment]
Yep, I would say it's our safest bet to accept Buffers and base64 strings. According to my testing, you can call `.toString('base64')` to a base64 string and it just returns the original base64 string, so that's probably not an issue and in that way caters for both allowed input types.

In your if statement, you could do something like this:

```js
if ( !(Buffer.isBuffer(msg.payload) || (typeof msg.payload === 'string' && /some_regexp/.test(msg.payload)))) {
      node.error("Input should be a Buffer or a ??????????", msg);
      node.status({fill:"red",shape:"ring", "Invalid input"});
}
```

RegExp for checking if string is a valid base64 string:
https://stackoverflow.com/a/8571649

About the 'no preview available' image: 

I would maybe prefer using a constructed SVG element for telling the user there's no preview available rather than using a static image. Maybe we could for instance [node.send](https://github.com/rikukissa/node-red-contrib-image-output/blob/master/image-output/image-output.js#L9) `data: null` back to the browser in cases where the `msg.payload` doesn't pass our validation.

**Comment by bartbutenaers** [comment]
all 3 topics above are currently implemented in the different pull requests.  I will close this issue, and discuss these items in their pull requests (if necessary).
